const data = {
    products: [{
        _id: 1,
        name: 'sougayliang',
        image: '/images/fishingRod/sougayliang.jpg',
        price: 200,
        brand: "Nike",
        numberReviews: 1,
        description: "This is my highest products",
        rating: 1.5,
        countInStock: 10,
    }, {
        _id: 2,
        name: 'sougayliangFull',
        image: '/images/fishingRod/sougayliangFull.jpg',
        price: 300,
        brand: "Nike2",
        numberReviews: 2,
        description: "This is my highest products",
        rating: 2.5,
        countInStock: 20,
    }, {
        _id: 3,
        name: 'Zebco33',
        image: '/images/fishingRod/Zebco33.jpg',
        price: 400,
        brand: "Zebco",
        numberReviews: 3,
        description: "This is my highest products",
        rating: 3.5,
        countInStock: 30,
    }, {
        _id: 4,
        name: 'ZebcoRoamFull',
        image: '/images/fishingRod/ZebcoRoamFull.jpg',
        price: 500,
        brand: "Zebco",
        numberReviews: 4,
        description: "This is my highest products",
        rating: 4.5,
        countInStock: 40,
    }, {
        _id: 5,
        name: 'SougayilangSpeed',
        image: '/images/fishingRod/SougayilangSpeed.jpg',
        price: 70,
        brand: "Zebco",
        numberReviews: 5,
        description: "This is my highest products",
        rating: 4.5,
        countInStock: 50,
    },
    {
        _id: 6,
        name: 'ZebcoSpincast',
        image: '/images/fishingRod/ZebcoSpincast.jpg',
        price: 70,
        brand: "Zebco",
        numberReviews: 6,
        description: "This is my highest products",
        rating: 5.5,
        countInStock: 0,
    }]
}
export default data;

