import bcrypt from "bcryptjs";
const data = {
    users: [
        {
            name: "Basir",
            email: "admin2@example.com",
            password: bcrypt.hashSync("1234", 8),
            isAdmin: true,
        },
        {
            name: "John",
            email: "user2@example.com",
            password: bcrypt.hashSync("1234", 8),
            isAdmin: false,
        },
    ],
    products: [
        {
            name: "sougayliang",
            image: "/images/fishingRod/sougayliang.jpg",
            category: "fishingRod",
            price: 200,
            brand: "Nike",
            numberReviews: 1,
            description: "This is my highest products",
            rating: 1.5,
            countInStock: 10,
        },
        {
            name: "sougayliangFull",
            image: "/images/fishingRod/sougayliangFull.jpg",
            category: "fishingRod",
            price: 300,
            brand: "Nike2",
            numberReviews: 2,
            description: "This is my highest products",
            rating: 2.5,
            countInStock: 20,
        },
        {
            name: "Zebco33",
            image: "/images/fishingRod/Zebco33.jpg",
            category: "fishingRod",
            price: 400,
            brand: "Zebco",
            numberReviews: 3,
            description: "This is my highest products",
            rating: 3.5,
            countInStock: 30,
        },
        {
            name: "ZebcoRoamFull",
            image: "/images/fishingRod/ZebcoRoamFull.jpg",
            category: "fishingRod",
            price: 500,
            brand: "Zebco",
            numberReviews: 4,
            description: "This is my highest products",
            rating: 4.5,
            countInStock: 40,
        },
        {
            name: "SougayilangSpeed",
            image: "/images/fishingRod/SougayilangSpeed.jpg",
            category: "fishingRod",
            price: 70,
            brand: "Zebco",
            numberReviews: 5,
            description: "This is my highest products",
            rating: 4.5,
            countInStock: 50,
        },
        {
            name: "ZebcoSpincast",
            image: "/images/fishingRod/ZebcoSpincast.jpg",
            category: "fishingRod",
            price: 70,
            brand: "Zebco",
            numberReviews: 6,
            description: "This is my highest products",
            rating: 5.5,
            countInStock: 0,
        },
    ],
};
export default data;
